---
title: "final_project.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
load("./data/fina.rda")
```

```{r}
# Denormalize, combining results, phases (a.k.a. heats), events
detailed_results <- fina_join()
```

## Filter to separate competitions (same named competitions)
## 99 competitions 
```{r}
comps <- detailed_results %>% group_by(competition) %>% summarise(n = n())
sepdetailed_results <- detailed_results %>% separate(col = competition, 
                                                     into = c("competitionname", "year"),
                                                     sep = -4) 
sepdetailed_results

word(competitionname, start = 205, end = 259, sep = fixed)

test1 <- finaldetailed_results %>% group_by(compname) %>% summarise(n = n())
sepdetailed_results %>% group_by(series) %>% summarise (n = n())
```

```{r}

```

## Filter by competition
```{r}
test1 <- detailed_results %>% filter(series == "Olympic Games")

```

## Filter by event (buttons?)
```{r}
test2 <- test1 %>% filter(style == "Medley")

```

## Filter by length of the event (buttons?)
```{r}
test3 <- test2 %>% filter(distance == "200")
```

## Filter by whether the even is a relay
```{r}
test4 <- test3 %>% filter(relay == FALSE)
```

## Filter by the year
```{r}
test5 <- test4 %>% filter(year == 2008)
```

```{r}
test5
```

## Filter by gender
```{r}
test6 <- test5 %>% filter(gender == "Men")

test6 %>% group_by(phase_label) %>% summarise(n = n())
test7 <- test6 %>% filter(phase_label == "Final")

```

## Make a table of the three winners, their country, and their time
```{r}
test7 <- test6 %>% filter(phase_label == "Final")
test8 <- test7 %>% filter(rank == 1 | rank == 2 | rank == 3) %>% select(rank, ioc_code, family_name, first_name, time)
test8
```

## Olympic Games worked
## 

```{r}

```



