---
title: "Final Write-up"
output: html_document
---

## The project I chose to do examines professional swimming results throughout different series and years. I chose data from the Fina website, which is a federation for competitions in water sports and it is recognized by the Olympic Committee. The data includes data spanning all the way back to 1924 and goes up until 2019. Within the data set there are many different variables including swimmers’ names, times, and countries. The data also included what series the event was from, which simply separates them by the competition (World Cup, Olympics, Youth Olympics, etc.). The purpose of my app was to organize this data, so that it is more easily readable and easier to see specific combinations of the data that were not previously shown in the data set. I chose to make a shiny app to do this, therefore the user can choose events very specifically and choose what data they want to see. 
## The visualization within the app with the title “How The Average Swim Time Has Changed Over The Years” is an example of expressing uncertainty. The point of this graph in the app was to be able to show how much faster people have become as a whole, so that is why I used the average. However, since the average was taken from hundreds of different times, I had to show the uncertainty in the graph. So, in this graph I chose to include error bars to show this. I also chose to make this into a plotly graph. Plotly makes the graph interactive, so the user can scan over the graph to look at specific years and average times. Since the axes on the graph may make it difficult to read exact numbers, plotly allows the user to compare exact numbers as well. 
## The other visualizations shown are tables, due to the type of data I wanted to show. The first table shows the top three finishers. This visualization was mostly just for the user to see a quick idea of the top finishers and what their time was for each year if they wanted to. The second table in the column of “Medals Won by Country Each Year” is an organized medal tally for each country and any year the user selects. I chose to include this because many people like to compare medals by countries. It is organized by the type of medal and also includes the total medals. It is organized from the highest number of total numbers to the lowest number and does not show any countries that won 0 medals. Since, there are so many factors here I decided not to show this through a graph, but through a table because the user can compare the values more easily. 
## There are many things I would have done if I had more time and no limitations. If I had more time and was able to obtain this data, I would have gotten data on the pools themselves and used that to help compare. Such as the dimensions and the shape of the pool because that can change the drag in the pool. I also would have hopefully compared the lanes within this comparison because each lane has a different drag, so that can impact how fast swimmers go as well. Also, (this would probably be the most difficult) get the suit information because many swimmers use special suits now that allow less drag, but not all of these suits are the same and they didn’t used to have these, so to compare how suits impact time as well. 
